config/routes.rb
Rails.application.routes.draw do

  root 'problems#index'
  post '/' => 'problems#index'
  get 'problems' => 'problems#index' 
  post 'problems' => 'problems#index'  

  get 'user/login' => 'user#login' , as: :login
  get 'user/logout' => 'user#logout' , as: :logout
  post 'user/login' => 'user#login'

  get "problems/pwn100"
  get "problems/pwn200"
  get "problems/pwn300"
  get "problems/sqlpwn"

end

app/models/flag.rb
class Flag < ActiveRecord::Base

	validates :question, :flag , presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :username, :password_digest, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  def check_login_state
	  if session[:username] == nil
		  flash[:error] = "Please login first"
		  redirect_to :login
	  end
  end

		  
	  

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/controllers/problems_controller.rb
require 'digest/md5'

class ProblemsController < ApplicationController

	before_action :check_login_state	


	def index
		if request.method == "POST"
			ans = Flag.find_by_question params[:user][:question]
			if ans.flag == params[:user][:flag]
				flash.now[:success] = "You got the flag!!"
			else
				flash.now[:error] = "T __ T "
			end

		end

		@question_list = Array.new
		Flag.all.each do |q|
			@question_list.push(q.question)
		end
		render :index
	end

	def pwn100
		send_file("#{Rails.root}/public/pwn100.tgz",filename:"pwn100-"+Digest::MD5.hexdigest('pwn100')+".tgz")
	end

	def pwn200
		send_file("#{Rails.root}/public/pwn200.tgz",filename:"pwn200-"+Digest::MD5.hexdigest('pwn200')+".tgz")
	end

	def pwn300
		send_file("#{Rails.root}/public/pwn300.tgz",filename:"pwn300-"+Digest::MD5.hexdigest('pwn300')+".tgz")
	end

	def sqlpwn
		send_file("#{Rails.root}/public/sqlpwn.tgz",filename:"sqlpwn-"+Digest::MD5.hexdigest('sqlpwn')+".tgz")
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	

	def login
		if request.method == "POST"
			@user = User.find_by_username params[:user][:username]
			if @user.nil? || !(@user.authenticate params[:user][:password])
				flash[:error] = "Username or password incorrect"
				session.delete :username
				redirect_to :login
			else
				flash[:success] = "Login Success!!"
				session[:username] = @user.username
				redirect_to :root
			end
		end
	end

	def logout
		session.clear
		flash[:success] = "Logout Success!!"
		redirect_to :login
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_error_flash.html.erb
<% if flash[:error] %>
<div class="row">
	<div class="col s12 m12 l12">
	  <div class="card light-blue accent-3">
		<div class="card-content white-text">
			<span class="card-title">Failed</span>
			<p><%=flash[:error]%></p>
		</div>
	  </div>
	</div>
</div>	
	

<% end %>

<% if flash[:success] %>
<div class="row">
	<div class="col s12 m12 l12">
	  <div class="card light-blue accent-3">
		<div class="card-content white-text">
			<span class="card-title">Success</span>
			<p><%=flash[:success]%></p>
		</div>
	  </div>
	</div>
</div>	
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer-copyright">
	<div class="container">
		Made by
		<a class="brown-text text-lighten-3" href="#">Iver , Alfonzo , Breeze</a> 
		with all the ♥
	</div>
</div>

app/views/layouts/_menu.html.erb
<div class="nav-wrapper container">
	<a href="<%= root_path %>" class="brand-logo"> One Week CTF </a>
	<ul id="nav-mobile" class="right hide-on-med-and-down">
		<li><a href="<%= root_path %>"#>Problems</a></li>
		<li>
			<% if session[:username] %>
				<%= link_to "Logout (#{session[:username]})", :logout %>
			<% else %>
				<%= link_to "Login", :login %>
			<% end %>
		</li>
	</ul>



</div>

app/views/layouts/_modal.html.erb
<div id="<%= question %>" class="modal">                                                                                                                                                       
	<div class="modal-content">
		<h4>Flag Submit</h4>
		<div class="row">
			<%=form_tag({controller: :problems,action: :index } ,{class: "col s12"} ) do %>
				<div class="row">
					<div class="input-field col s6">
						<i class="material-icons prefix">vpn_key</i>
						<%= text_field :user, :flag, class: "validate" %>
						<label for="icon_prefix">flags</label>
					</div>
				</div>
				<%= hidden_field :user, :question, :value => question %>
				<div class="row">
					<%= submit_tag "Send", class: " waves-effect waves-light btn"  %>
				</div>
			<% end %> 
		</div>
	</div>
	<div class="modal-footer">
		<a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Close</a>
	</div>

</div>

app/views/layouts/_web.html.erb
<%  part = question.split('-')  %>

<% if part[0] == "web" %>

<div class="row">
	<div class="col s12 m6 l4">
		<div class="card blue-grey darken-1">
			<div class="card-content white-text">
				<span class="card-title">Web 100</span>
				<p>Please see the website there</p>
			</div>
			<div class="card-action">
				<a href="#">Website</a>
				<a class="  modal-trigger" href="#web-100">Submit the flag</a>
			</div>
		</div>
	</div>
</div>                   

<% elsif part[0] == "pwn" %>

<div class="row">
	<div class="col s12 m6 l4">
		<div class="card blue-grey darken-1">
			<div class="card-content white-text">
				<span class="card-title">Web 100</span>
				<p></p>
			</div>
			<div class="card-action">
				<a class="  modal-trigger" href="#web-100">Submit the flag</a>
			</div>
		</div>
	</div>
</div>                   

<% elsif part[0] == "misc" %>



<% elsif part[0] == "crypto" %>

<% end %>


                                      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>One Week CTF</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<!-- Nav bar -->
<div class="above_wrapper">
	<nav class=" indigo darken-1 " role="navigation"><%= render 'layouts/menu' %> </nav>
<div class="main ">
	<%= yield %>
</div>
<footer class=" indigo darken-1 page-footer footer_mod"><%= render 'layouts/footer' %></footer>
</div>

</body>
</html>

app/views/problems/index.html.erb
<div class="" >
	<%= render 'layouts/error_flash' %>

	<div class="row">
		<div class="col s12 m12 l4">
			<div class="card blue-grey darken-1">
				<div class="card-content white-text">
					<span class="card-title">Web 100</span>
					<p>See the detail..</p>
				</div>
				<div class="card-action">
					<a target="_blank" href="http://140.123.242.36:20001">Website</a>
					<a class="modal-trigger" href="#web-100">Submit flag</a>
				</div>
			</div>
		</div>

		<div class="col s12 m12 l4">
			<div class="card blue-grey darken-1">
				<div class="card-content white-text">
					<span class="card-title">Web 200</span>
					<p>Bypass it!</p>
				</div>
				<div class="card-action">
					<a target="_blank" href="http://140.123.242.36:20002">Website</a>
					<a class="modal-trigger" href="#web-200">Submit flag</a>
				</div>
			</div>
		</div>

		<div class="col s12 m12 l4">
			<div class="card blue-grey darken-1">
				<div class="card-content white-text">
					<span class="card-title">Web 300</span>
					<p>SQL Injection</p>
				</div>
				<div class="card-action">
					<a target="_blank" href="http://140.123.242.36:20003">Website</a>
					<a class="modal-trigger" href="#web-300">Submit flag</a>
				</div>
			</div>
		</div>
	</div>



	<div class="row">
		<div class="col s12 m12 l4">
			<div class="card blue-grey darken-1">
				<div class="card-content white-text">
					<span class="card-title">Web 400</span>
					<p>Please see the website there</p>
				</div>
				<div class="card-action">
					<%= link_to "Download", problems_sqlpwn_url ,  {:style => 'margin:3px'}%>
					<a target="_blank" style="margin:6px"href="http://140.123.242.36:30001">Website</a>
					<a class=" modal-trigger" href="#web-400">Submit</a>
				</div>
			</div>
		</div>

		<div class="col s12 m12 l4">
			<div class="card blue-grey darken-1">
				<div class="card-content white-text">
					<span class="card-title">Pwn 100</span>
					<p>nc 140.123.242.36 11111</p>
				</div>
				<div class="card-action">
					<%= link_to "Download", problems_pwn100_url %>
					<a class="  modal-trigger" href="#pwn-100">Submit flag</a>
				</div>
			</div>
		</div>

		<div class="col s12 m12 l4">
			<div class="card blue-grey darken-1">
				<div class="card-content white-text">
					<span class="card-title">Pwn 200</span>
					<p>nc 140.123.242.36 11112</p>
				</div>
				<div class="card-action">
					<%= link_to "Download", problems_pwn200_url %>
					<a class="  modal-trigger" href="#pwn-200">Submit flag</a>
				</div>
			</div>
		</div>
	</div>



	<div class="row">
		<div class="col s12 m12 l4">
			<div class="card blue-grey darken-1">
				<div class="card-content white-text">
					<span class="card-title">Pwn 300</span>
					<p>nc 140.123.242.36 11113</p>
				</div>
				<div class="card-action">
					<%= link_to "Download", problems_pwn300_url %>
					<a class="  modal-trigger" href="#pwn-300">Submit flag</a>
				</div>
			</div>
		</div>
	</div>

	<%= render partial: "/layouts/modal", collection: @question_list , as: :question %>

</div>

app/views/user/login.html.erb
<div class="container">

	<%= render 'layouts/error_flash' %>

	<div class="section header" >
		<h5>Login</h5>
	</div>

	<%= form_tag('/user/login') do  %>
        <div class="row">
			<div class="input-field col s12">
				<%= text_field :user, :username %>
				<label for="username">User Name</label>
			</div>
		</div>
		<div class="row">
			<div class="input-field col s12">
			  <%= password_field :user,:password %>
			  <label for="password">Password</label>
			</div>
        </div>
		<%= submit_tag "Login" , class: "waves-effect waves-light btn" %>
	<% end %>
</div>